# Generated by Django 5.1 on 2024-09-08 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppLitobar", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="imagen",
            field=models.ImageField(blank=True, null=True, upload_to="mascotas/"),
        ),
    ]
