# Generated by Django 5.1 on 2024-09-08 03:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppLitobar", "0002_mascota_imagen"),
    ]

    operations = [
        migrations.AddField(
            model_name="cita",
            name="fecha_creacion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="cita",
            name="fecha_modificacion",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="cita",
            name="motivo",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="cita",
            name="veterinario",
            field=models.CharField(max_length=200),
        ),
    ]
