# Generated by Django 5.1 on 2024-09-08 16:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppLitobar", "0003_cita_fecha_creacion_cita_fecha_modificacion_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="fecha_edit",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="mascota",
            name="fecha_new",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
