# Generated by Django 5.1 on 2024-09-08 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppLitobar", "0005_cita_imagen_mascota"),
    ]

    operations = [
        migrations.AddField(
            model_name="mascota",
            name="fecha_nacimiento",
            field=models.DateField(blank=True, null=True),
        ),
    ]
